const HOSTED_URL = process.env.NEXT_PUBLIC_HOSTED_URL
const MERCHANT_ID = process.env.NEXT_PUBLIC_MERCHANT_ID
const PG_BASE_URL = process.env.NEXT_PUBLIC_PG_BASE_URL
const MERCHANT_NAME = process.env.NEXT_PUBLIC_MERCHANT_NAME
const API_PASSWORD = process.env.NEXT_PUBLIC_API_PASSWORD
const AUTH_TOKEN = process.env.NEXT_PUBLIC_AUTH_TOKEN

const CHECKOUT_SESSION_KEY = 'MPGS_CHECKOUT_SESSION_ID'

export {
  HOSTED_URL,
  PG_BASE_URL,
  MERCHANT_ID,
  MERCHANT_NAME,
  API_PASSWORD,
  AUTH_TOKEN,
  CHECKOUT_SESSION_KEY
}
